# -*- coding: utf-8 -*-
# ruff: noqa
# pyright: reportAttributeAccessIssue=false
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: navigation_map.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'navigation_map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14navigation_map.proto\x12\x17robot.api.v1.navigation\x1a\x1bgoogle/protobuf/empty.proto\"W\n\x10NavigationTarget\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x0b\n\x03x_m\x18\x03 \x01(\x02\x12\x0b\n\x03y_m\x18\x04 \x01(\x02\x12\x0f\n\x07yaw_rad\x18\x05 \x01(\x02\"\xaf\x01\n\x19NavigationTargetsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08map_name\x18\x03 \x01(\t\x12\x0e\n\x06map_id\x18\x04 \x01(\x04\x12\x12\n\nresolution\x18\x05 \x01(\x02\x12:\n\x07targets\x18\x06 \x03(\x0b\x32).robot.api.v1.navigation.NavigationTarget2z\n\x14NavigationMapService\x12\x62\n\x14GetNavigationTargets\x12\x16.google.protobuf.Empty\x1a\x32.robot.api.v1.navigation.NavigationTargetsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navigation_map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONTARGET']._serialized_start=78
  _globals['_NAVIGATIONTARGET']._serialized_end=165
  _globals['_NAVIGATIONTARGETSRESPONSE']._serialized_start=168
  _globals['_NAVIGATIONTARGETSRESPONSE']._serialized_end=343
  _globals['_NAVIGATIONMAPSERVICE']._serialized_start=345
  _globals['_NAVIGATIONMAPSERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
